import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const INDEX_PATH = path.resolve(__dirname, '../index.html');

function readIndex() {
  return fs.readFileSync(INDEX_PATH, 'utf8');
}

test('happy path: index exports game rendering pipeline markers', () => {
  const src = readIndex();
  assert.match(src, /drawGolfer/);
  assert.match(src, /worldToScreen/);
  assert.match(src, /render_game_to_text/);
  assert.match(src, /function drawEnvironment/);
  assert.match(src, /projectWorldToScreen/);
  assert.match(src, /buildFlightCamera/);
  assert.match(src, /sampleTrajectoryPreview/);
});

test('boundary: immediate launch and multi preset camera UI keywords should exist', () => {
  const src = readIndex();
  assert.match(src, /2\. 현재 샷/);
  assert.match(src, /1\. 현재 입력값 확인과 비행 추적/);
  assert.match(src, /3\. 현재 입력값 조정/);
  assert.match(src, /1\. 퍼트 결과와 거리감 확인/);
  assert.match(src, /2\. 퍼트 결과/);
  assert.match(src, /3\. 퍼터 세팅과 가이드/);
  assert.match(src, /현재 방향 입력값/);
  assert.match(src, /현재 볼 입력값/);
  assert.match(src, /퍼터 세션 가이드/);
  assert.match(src, /퍼터 세션 이동/);
  assert.match(src, /거리감 훈련/);
  assert.match(src, /홀까지 거리 선택/);
  assert.match(src, /수동 또는 모션 스트로크 준비/);
  assert.match(src, /퍼트 실행과 결과 확인/);
  assert.match(src, /고급 센서 모드 열기/);
  assert.match(src, /빠른 거리감 훈련이 기본/);
  assert.match(src, /카메라 모드/);
  assert.match(src, /볼 추적/);
  assert.match(src, /티박스 고정/);
  assert.match(src, /공을 따라 비행 추적/);
  assert.match(src, /첫 화면 시점을 유지한 채 비행 보기/);
  assert.match(src, /C 다음 \/ Shift\+C 이전/);
  assert.match(src, /좌드래그 이동 · 우드래그 회전 · 휠 줌 · Esc 리셋/);
  assert.match(src, /시점 리셋/);
  assert.match(src, /바로 실행/);
  assert.match(src, /지금 실행하면 현재 입력값으로 바로 칩니다\./);
  assert.match(src, /마지막 착지/);
  assert.match(src, /실시간 비행/);
  assert.match(src, /실시간 비행 정보 없음/);
  assert.match(src, /기록 단위/);
  assert.match(src, /직전 샷 기록과 HUD 표시에 적용/);
  assert.match(src, /직전 샷 없음/);
  assert.match(src, /현재 상태/);
  assert.match(src, /다음 샷 준비/);
  assert.match(src, /현재 샷 · 직전 샷 · 변화/);
  assert.match(src, /현재 퍼트 · 직전 퍼트 · 변화/);
  assert.match(src, /지금 조정한 값은 다음 실행에 반영됩니다\./);
  assert.match(src, /현재 방향 입력값은 기본값이고, 현재 볼 입력값은 입력창 값이 적용됩니다\./);
  assert.match(src, /현재 입력값이 현재 샷 입력값과 일치합니다\./);
  assert.match(src, /현재 샷 입력값과 다른 항목:/);
  assert.match(src, /\(변경됨\)/);
  assert.match(src, /아직 현재 샷이 없습니다\./);
  assert.match(src, /첫 샷을 실행하면 현재 샷이 표시됩니다\./);
  assert.match(src, /볼 스피드 \(Ball Speed\)/);
  assert.match(src, /캐리 \(Carry\)/);
  assert.match(src, /토탈 \(Total\)/);
  assert.match(src, /오프라인 \(Offline\)/);
  assert.match(src, /볼 스피드 \(mph\)/);
  assert.match(src, /사이드스핀 \(rpm\)/);
  assert.match(src, /백스핀 \(rpm\)/);
  assert.match(src, /남은 거리 \(Remaining\)/);
  assert.match(src, /굴러간 거리 \(Roll\)/);
  assert.match(src, /라인 오차 \(Line\)/);
  assert.match(src, /스트로크 속도 \(Stroke\)/);
  assert.match(src, /입력 오버뷰/);
  assert.match(src, /결과 오버뷰/);
  assert.match(src, /세부값 보기/);
  assert.match(src, /실험 조건 초기화/);
  assert.doesNotMatch(src, /고정 시점/);
  assert.doesNotMatch(src, /티박스 대각/);
  assert.doesNotMatch(src, /타깃 정면/);
  assert.doesNotMatch(src, /측면 분석/);
  assert.doesNotMatch(src, /길게 눌러 다시 치기/);
  assert.doesNotMatch(src, /놓으면 발사/);
  assert.doesNotMatch(src, /길게 눌러 실행/);
});

test('regression: metric panel hierarchy and comparison copy remain available', () => {
  const src = readIndex();
  const ballSpeedIndex = src.indexOf('볼 스피드 (Ball Speed)');
  const carryIndex = src.indexOf('캐리 (Carry)');
  const totalIndex = src.indexOf('토탈 (Total)');
  const offlineIndex = src.indexOf('오프라인 (Offline)');
  const comparisonIndex = src.indexOf('현재 샷 · 직전 샷 · 변화');

  assert.ok(ballSpeedIndex >= 0);
  assert.ok(carryIndex > ballSpeedIndex);
  assert.ok(totalIndex > carryIndex);
  assert.ok(offlineIndex > totalIndex);
  assert.ok(comparisonIndex > offlineIndex);
});

test('regression: immediate launch hooks and camera preset functions should exist', () => {
  const src = readIndex();
  assert.match(src, /id="hud-ball-speed"/);
  assert.match(src, /id="hud-club-head-speed"/);
  assert.match(src, /id="hud-impact-quality"/);
  assert.match(src, /id="hud-smash"/);
  assert.match(src, /id="ready-meter-fill"/);
  assert.match(src, /id="ready-meter-label"/);
  assert.match(src, /id="comparison-summary"/);
  assert.match(src, /id="comparison-context"/);
  assert.match(src, /id="comparison-current-value"/);
  assert.match(src, /id="comparison-previous-value"/);
  assert.match(src, /id="comparison-change-value"/);
  assert.match(src, /id="control-sidebar"/);
  assert.match(src, /id="hud-toggle"/);
  assert.match(src, /id="control-toggle"/);
  assert.match(src, /id="panel-scrim"/);
  assert.match(src, /id="session-state"/);
  assert.match(src, /id="game-viewport"/);
  assert.match(src, /id="putter-shortcut-tab"/);
  assert.match(src, /id="game-stage-heading"/);
  assert.match(src, /id="hud-panel-heading"/);
  assert.match(src, /id="control-sidebar-heading"/);
  assert.match(src, /id="ready-section-heading"/);
  assert.match(src, /id="ready-section-note"/);
  assert.match(src, /id="comparison-section-heading"/);
  assert.match(src, /id="session-input-overview"/);
  assert.match(src, /id="session-input-ball-key"/);
  assert.match(src, /id="session-input-ball"/);
  assert.match(src, /id="session-input-backspin-key"/);
  assert.match(src, /id="session-input-backspin"/);
  assert.match(src, /id="session-input-sidespin-key"/);
  assert.match(src, /id="session-input-sidespin"/);
  assert.match(src, /id="session-result-overview"/);
  assert.match(src, /id="session-result-primary-key"/);
  assert.match(src, /id="session-result-primary"/);
  assert.match(src, /id="session-result-secondary-key"/);
  assert.match(src, /id="session-result-secondary"/);
  assert.match(src, /id="session-result-tertiary-key"/);
  assert.match(src, /id="session-result-tertiary"/);
  assert.match(src, /id="comparison-current-label"/);
  assert.match(src, /id="comparison-previous-label"/);
  assert.match(src, /id="comparison-change-label"/);
  assert.match(src, /id="aim-direction"/);
  assert.match(src, /id="camera-mode"/);
  assert.match(src, /id="camera-mode-row"/);
  assert.match(src, /id="camera-mode-note"/);
  assert.match(src, /id="camera-reset-btn"/);
  assert.match(src, /id="camera-reset-overlay"/);
  assert.match(src, /id="camera-overlay-controls"/);
  assert.match(src, /id="camera-overlay-hint"/);
  assert.match(src, /id="distance-unit"/);
  assert.match(src, /id="distance-unit-note"/);
  assert.match(src, /id="range-ball-input-card"/);
  assert.match(src, /id="putter-input-card"/);
  assert.match(src, /id="putter-motion-card"/);
  assert.match(src, /id="putter-guide-card"/);
  assert.match(src, /id="putter-guide-summary"/);
  assert.match(src, /id="putter-step-distance"/);
  assert.match(src, /id="putter-step-distance-note"/);
  assert.match(src, /id="putter-step-input"/);
  assert.match(src, /id="putter-step-input-note"/);
  assert.match(src, /id="putter-step-result"/);
  assert.match(src, /id="putter-step-result-note"/);
  assert.match(src, /id="putter-advanced-link"/);
  assert.match(src, /function updateChrome/);
  assert.match(src, /function setPutterGuideStepState/);
  assert.match(src, /function updatePutterGuide/);
  assert.match(src, /function formatHudStatus/);
  assert.match(src, /function triggerLaunch/);
  assert.match(src, /function formatBallInputSummary/);
  assert.match(src, /function formatRecentFlightSummary/);
  assert.match(src, /function getDistanceUnitConfig/);
  assert.match(src, /function formatDistanceValue/);
  assert.match(src, /function formatComparisonSummary/);
  assert.match(src, /function formatComparisonContext/);
  assert.match(src, /function formatShotInputSummary/);
  assert.match(src, /function getLiveFlightMetrics/);
  assert.match(src, /function formatCurveDirection/);
  assert.match(src, /function formatLiveFlightSummary/);
  assert.match(src, /function renderShotHistory/);
  assert.match(src, /function samplePointSeries/);
  assert.match(src, /function buildShotTrajectorySamples/);
  assert.match(src, /function snapshotCurrentInputs/);
  assert.match(src, /function sameNullableNumber/);
  assert.match(src, /function hasPendingInputChanges/);
  assert.match(src, /function getChangedInputKeys/);
  assert.match(src, /function formatChangedInputSummary/);
  assert.match(src, /function formatInputHeading/);
  assert.match(src, /function formatBallInputDetailValue/);
  assert.match(src, /function formatSessionResultDetail/);
  assert.match(src, /function currentResultReferenceKind/);
  assert.match(src, /function formatResultReferenceLabel/);
  assert.match(src, /function formatCurrentStateSummary/);
  assert.match(src, /function formatResultStatusNote/);
  assert.match(src, /function formatNextActionHint/);
  assert.match(src, /function formatReadyMeterLabel/);
  assert.match(src, /function getReadyMeterProgress/);
  assert.match(src, /function buildShotRecord/);
  assert.match(src, /function isSuccessfulShotRecord/);
  assert.match(src, /function parseInputBound/);
  assert.match(src, /function refreshInputDrivenState/);
  assert.match(src, /function setBallSpeedInputMph/);
  assert.match(src, /function nudgeBallSpeedInput/);
  assert.match(src, /function setSideSpinInputRpm/);
  assert.match(src, /function nudgeSideSpinInput/);
  assert.match(src, /function setBackSpinInputRpm/);
  assert.match(src, /function nudgeBackSpinInput/);
  assert.match(src, /function isCompactLayout/);
  assert.match(src, /function syncPanelToggleState/);
  assert.match(src, /function setFoldPanel/);
  assert.match(src, /function toggleFoldPanel/);
  assert.match(src, /function closeFoldPanels/);
  assert.match(src, /function getCameraModeProfile/);
  assert.match(src, /function buildFixedCamera/);
  assert.match(src, /function setCameraMode/);
  assert.match(src, /function syncCameraMode/);
  assert.match(src, /function cycleCameraMode/);
  assert.match(src, /function restoreCameraModePreference/);
  assert.match(src, /function setDistanceUnit/);
  assert.match(src, /function restoreDistanceUnitPreference/);
  assert.match(src, /function interruptToReady/);
  assert.match(src, /function formatCameraModeLabel/);
  assert.match(src, /function formatCameraBadgeTitle/);
  assert.match(src, /function formatCameraBehaviorHint/);
  assert.match(src, /function formatCameraHint/);
  assert.match(src, /function formatCameraControlNote/);
  assert.match(src, /function announceCameraMode/);
  assert.match(src, /function isManualCameraEnabled/);
  assert.match(src, /function updateCameraManualDirty/);
  assert.match(src, /function resetManualCamera/);
  assert.match(src, /function syncViewportLayoutState/);
  assert.match(src, /function syncCameraInteractionUI/);
  assert.match(src, /function beginCameraDrag/);
  assert.match(src, /function endCameraDrag/);
  assert.match(src, /function applyCameraPan/);
  assert.match(src, /function applyCameraOrbit/);
  assert.match(src, /function applyCameraZoom/);
  assert.match(src, /function updateCameraDrag/);
  assert.match(src, /function formatStartButtonLabel/);
  assert.match(src, /function playImpactCue/);
  assert.match(src, /function playLandingCue/);
  assert.match(src, /function playReadyCue/);
  assert.match(src, /function drawHistoricalTrails/);
  assert.match(src, /function drawLandingMarkers/);
  assert.match(src, /function drawReadyPulse/);
  assert.match(src, /function drawCameraModeBadge/);
  assert.match(src, /function drawFlightTelemetryBadge/);
  assert.match(src, /function drawLoopStateBadge/);
  assert.match(src, /if \(!state\.ball\.moving && \(!state\.currentShot \|\| isPutterSession\(\)\)\) drawAim\(\);/);
  assert.match(src, /const AUTO_READY_SECONDS = 2/);
  assert.match(src, /const MAX_SHOT_HISTORY = 7/);
  assert.match(src, /const MAX_HISTORY_TRAJECTORY_SAMPLES = 96/);
  assert.match(src, /const HOTKEY_BALL_SPEED_STEP_MPH = 1/);
  assert.match(src, /const HOTKEY_SIDE_SPIN_STEP_RPM = 50/);
  assert.match(src, /const HEIGHT_COMPACT_BREAKPOINT = 820/);
  assert.match(src, /const CAMERA_MODES = \[\s*"follow",\s*"fixed-tee",?\s*\]/s);
  assert.match(src, /const NEUTRAL_SWING = Object\.freeze\(\{/);
  assert.match(src, /const compactLayoutQuery = window\.matchMedia\("\(max-width: 1240px\)"\)/);
  assert.match(src, /cameraManual: createDefaultCameraManual\(\)/);
  assert.match(src, /isHeightCompact: false/);
  assert.match(src, /cameraMode: state\.cameraMode/);
  assert.match(src, /distanceUnit: state\.distanceUnit/);
  assert.match(src, /manualActive: state\.cameraManual\.active/);
  assert.match(src, /manualDirty: state\.cameraManual\.dirty/);
  assert.match(src, /heightCompact: state\.isHeightCompact/);
  assert.match(src, /localStorage\.setItem\(CAMERA_MODE_STORAGE_KEY, state\.cameraMode\)/);
  assert.match(src, /localStorage\.setItem\(DISTANCE_UNIT_STORAGE_KEY, state\.distanceUnit\)/);
  assert.match(src, /shell\.dataset\.heightCompact = state\.isHeightCompact \? "true" : "false"/);
  assert.match(src, /canvas\.dataset\.cameraInteraction =/);
  assert.match(src, /이 패널은 현재 샷 핵심 지표와 직전 샷 변화를 보여줍니다\./);
  assert.match(src, /현재 샷이 아직 없습니다\./);
  assert.match(src, /새 샷을 계산 중이며 현재 샷 값은 새 결과가 확정되면 갱신됩니다\./);
  assert.match(src, /입력값이 바뀌었고, 다음 실행이 끝나면 현재 샷이 새 결과로 바뀝니다\./);
  assert.match(src, /현재 샷 핵심 4개를 먼저 읽고, 아래에서 직전 샷 변화를 확인하세요\./);
  assert.match(src, /현재 샷 핵심 4개가 먼저 보이고, 비교 정보는 그다음에 읽힙니다\./);
  assert.match(src, /초 뒤 다시 칠 수 있습니다\./);
  assert.match(src, /다음 샷 준비 완료\. 지금 바로 다시 칠 수 있습니다\./);
  assert.match(src, /이전 샷은 계속 비행 중이고, 다시 조준할 수 있습니다\./);
  assert.match(src, /샷 \$\{state\.previousShot\.shotNo\} · 캐리/);
  assert.match(src, /state\.recentShots/);
  assert.match(src, /state\.detachedFlights/);
  assert.match(src, /카메라가 \$\{formatCameraModeLabel\(\)\}으로 전환됨/);
  assert.match(src, /Shift\+C 입력 반영됨/);
  assert.match(src, /C 입력 반영됨/);
  assert.match(src, /메뉴 선택 반영됨/);
  assert.match(src, /지금 실행하면 변경된 입력으로 바로 다시 칩니다\./);
  assert.match(src, /지금 실행하면 같은 입력으로 바로 다시 칩니다\./);
  assert.match(src, /지금 실행하면 현재 입력값으로 바로 칩니다\./);
  assert.match(src, /A \/ D: 방향/);
  assert.match(src, /Q \/ E: 사이드스핀/);
  assert.match(src, /W \/ S: 볼 스피드/);
  assert.match(src, /R \/ F: 백스핀/);
  assert.match(src, /C: 카메라/);
  assert.match(src, /샷 정보/);
  assert.match(src, /입력 패널/);
  assert.match(src, /A\/D 또는 ArrowLeft\/ArrowRight/);
  assert.match(src, /ballSpeed: isPutterSession\(\) \? "W\/S 수동 스트로크 속도" : "W\/S"/);
  assert.match(src, /sideSpin: isPutterSession\(\) \? "Q\/E 홀 거리" : "Q\/E"/);
  assert.match(src, /backSpin: isPutterSession\(\) \? "R\/F 그린 감쇠" : "R\/F"/);
  assert.match(src, /Space: 바로 실행/);
  assert.match(src, /Space 실행 \/ 비행 중 재준비/);
  assert.match(src, /Esc: 시점 리셋/);
  assert.match(src, /Shift\+F: 전체화면/);
  assert.doesNotMatch(src, /function beginLaunchCharge/);
  assert.doesNotMatch(src, /function releaseLaunchCharge/);
  assert.doesNotMatch(src, /shot_primed/);
  assert.doesNotMatch(src, /C 키 또는 메뉴에서 전환/);
});

test('regression: render payload still includes shot history and impact markers', () => {
  const src = readIndex();
  assert.match(src, /didImpact:\s*state\.model\.didImpact/);
  assert.match(src, /impactEffectCount:\s*state\.impactEffects\.length/);
  assert.match(src, /charging:\s*state\.charging/);
  assert.match(src, /charge:\s*Number\(state\.charge\.toFixed\(3\)\)/);
  assert.match(src, /ball:\s*\{\s*position:/s);
  assert.match(src, /metrics:\s*\{\s*carry:/s);
  assert.match(src, /liveFlight:\s*liveFlight \?/);
  assert.match(src, /curveDirection:\s*formatCurveDirection\(liveFlight\.curveMeters\)/);
  assert.match(src, /distanceUnit:\s*state\.distanceUnit/);
  assert.match(src, /currentShot:\s*serializeShotRecord\(state\.currentShot\)/);
  assert.match(src, /previousShot:\s*serializeShotRecord\(state\.previousShot\)/);
  assert.match(src, /recentShots:\s*state\.recentShots\.map/);
  assert.match(src, /detachedFlights:\s*state\.detachedFlights\.map/);
  assert.match(src, /sessionContract/);
  assert.match(src, /buildSessionContractPayload/);
  assert.match(src, /restoreSessionKind/);
  assert.match(src, /persistSessionKind/);
  assert.match(src, /change:\s*change \?/);
  assert.match(src, /launchAzimuthDeg/);
  assert.match(src, /mode:\s*state\.mode/);
});
